version: '3.7'

services:
  web:
    image: backend_api_web:latest
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 0 --keep-alive 3600 --backlog 2048
    volumes:
      - ./app/public:/home/app/web/public
      - ./app/public/media:/home/app/web/public/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis

  db:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5431:5432
    env_file:
      - ./.env.prod.db

  nginx:
    restart: always
    image: backend_api_nginx:latest
    build: ./nginx
    volumes:
      - ./app/public:/home/app/web/public
      - ./app/public/media:/home/app/web/public/media
    ports:
      - 3000:80
    depends_on:
      - web

  redis:
    restart: always
    image: redis:5.0.12-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis/data

volumes:
  postgres_data:
  redis_data: